# Generated by Django 5.2.17 on 2026-08-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('debt_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qarz balansi')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami summa')),
                ('payment_type', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Plastik karta'), ('qarz', 'Nasiya (qarz)')], default='naqd', max_length=20, verbose_name="To'lov turi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.branch', verbose_name='Filial')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Sotuv (chek)',
                'verbose_name_plural': 'Sotuvlar (cheklar)',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi (sotuv paytida)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Chek')),
            ],
            options={
                'verbose_name': 'Chek qatori',
                'verbose_name_plural': 'Chek qatorlari',
            },
        ),
    ]
